### ISSUE TITLE
Escrever o documento do Backlog do produto

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-PlantJammer#23]
## Descrição

Backlog é uma lista com prioridades dos requisitos ou funcionalidades do projeto que fornecem valor comercial ao cliente. Geralmente utilizado na técnica de desenvolvimento ágil, SCRUM. Os itens podem ser adicionados a esse registro em qualquer momento. Cabe ao gerente de produto avaliar o registro e atualizar as prioridades conforme requisitado.

O Backlog do produto deve ser:

Detalhado o suficiente para que os desenvolvedores consigam entregar as funcionalidades ou histórias de usuário descritas.
Estimável de forma a ser possível dizer quanto tempo levará para implementar a funcionalidade.
Emergente de forma que possa ser continuamente atualizado.
Priorizado de forma a trazer maior valor para o cliente.
Backlogs são focados em histórias de usuário, e contém sua descrição, identificação e priorização.

## Tarefas
- [ ] Analisar requisitos
- [ ] Criar tasks e possiveis épicos
- [ ] (Se necessário) criar um tema
- [ ] Separar a task em features

## Critérios de aceitação
- [ ] Features corretamente priorizadas
- [ ] Tasks rastreadas com o cada requisito levantado
- [ ] Épicos envolvendo tasks correlacionadas
- [ ] Documento sobre Backlog do produto
    - [ ] Bibliografia/Referência bibliografica
    - [ ] Introdução/Metodologia
    - [ ] Versionamento do documento

## Referências

LuizTools. Product Backlog - Introdução. Disponível em: https://www.youtube.com/watch?v=z4ubaBwjCsU&feature=youtu.be

**Comment by LeoSilvaGomes** [comment]
O Backlog do produto visa a análise dos requisitos levantados e transforma-los em tarefas, épicos e temas, com o objetivo de priorizar a criação do app e ter o controle de features. O Backlog do produto é feito pelo Product Owner que tem visão mais detalhe do projeto e das relações com os clientes.
