### ISSUE TITLE
Documentação da 2º Sprint

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-PlantJammer#47]
## Documentação da 2º Sprint

Descrição | Data
--------- | ------
| **Data de início**   | 22 de fevereiro |
| **Data de término** | 01 de março |

| Issue | Responsável | Concluída  | Causa |
| :-: | :-:  | :-: | :-:  |
| Criar documento do Storyboard #33 | @VictorJorgeFGA | ✔️ |
| Escrever o documento das Personas #32 | @hugorochaffs |✖️ |
| Escrever o documento de 5W2H #27 | @durvalcarvalho  | ✔️ |
| Realizar técnicas de Brainstrorm #12 | @joao15victor08  |✖️ |
| Realizar técnica de observação #14  | @LeoSilvaGomes  | ✔️ |

**Comment by LeoSilvaGomes** [comment]
A issue #32 e #12 entraram como divida técnica tendo em vista os estudos feitos pelo documento e analisando que os documento feitos ainda estão incompletos nos prs #52 e #51
