### ISSUE TITLE
Criar tabela de tecnologias

### ISSUE THREAD

**Issue by durvalcarvalho** [Requisitos-de-Software/2020.2-PlantJammer#9]
## Criar tabela de tecnologias

Deve exister em algum lugar uma tabela com todas as tecnologias que o grupo está usando ou irá usar durante a execução do projeto.

[Exemplo de tabela](https://github.com/Interacao-Humano-Computador/2020.1-BCE/blob/master/docs/README.md#-ferramentas-)

**Comment by hugorochaffs** [comment]
Feito!
